import Head from "next/head";
import Header from "../components/Header";
import { Container, Row, Col } from "react-bootstrap";
import styles from "../styles/Home.module.scss";
import Image from "next/image";
import logo from "../assets/img/1.jpg";
import pix from "../assets/img/pix.jpg";
import bb from "../assets/img/bb.png";
import zap from "../assets/img/zap.png";
import "bootstrap/dist/css/bootstrap.min.css";
import Link from "next/link";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Anjos Solidários - Araci-Bahia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <Container className="mb-5">
          <Row>
            <Col xs={12}>
              <h2>Colabore</h2>
              <p>
                Ajude dezenas famílias doando qualquer quantia através dos links
                abaixo:
              </p>
            </Col>
            <Col xs={12} md={4} className='mb-4'>
              <div className={styles.donate}>
                <Image
                  src={pix}
                  alt="Chave Pix dos Anjos Solidários"
                  width={200}
                  height={200}
                />
                <div>
                  <h2>Chave Pix</h2>
                  <p>48.796.055/0001-86</p>
                </div>
              </div>
            </Col>
            <Col xs={12} md={4} className='mb-4'>
              <div className={styles.donate}>
                <Image
                  src={bb}
                  alt="Banco do Brasil"
                  width={120}
                  height={120}
                />
                <div>
                  <h3>Banco do Brasil</h3>
                  <p>
                    Ag: 1456-7
                    <br />
                    CC: 36.893-8
                  </p>
                </div>
              </div>
            </Col>
            <Col xs={12} md={4} className={styles.article}>
              <Link
                href="https://wa.me/5575991920840"
                rel="noopener noreferrer"
                target="_blank"
              >
                <div className={styles.donate}>
                  <Image
                    src={zap}
                    alt="Anjos Solidários Whatsapp"
                    width={120}
                    height={120}
                  />
                  <div>
                    <h2>WhatsApp</h2>
                    <p>(75) 9 9192 0840</p>
                  </div>
                </div>
              </Link>
            </Col>
          </Row>
        </Container>
        <Container>
          <Row>
            <Col xs={12} md={5}>
              <div className={styles.image__container}>
                <Image
                  src={logo}
                  alt="Anjos Solidários Araci Bahia"
                  layout="fill"
                  className={styles.image}
                />
              </div>
            </Col>
            <Col xs={12} md={7} className={styles.about}>
              <h2>Quem somos</h2>
              <p>
                Somos uma ONG formada por mulheres da cidade de Araci/Bahia que
                tem o objetivo de ajudar pessoas doentes e acamadas. Através de
                doações e colaborações conseguimos fornecer fraldas geriátricas,
                materiais de higiene, pomada e remédios para diversas famílias
                carentes da nossa cidade.
              </p>
              <h2>Como ajudar?</h2>
              <p>
                Aceitamos doações em dinheiro através da nossa chave pix
                (48.796.055/0001-86) e doações de fraldas geriátricas em nossos
                pontos de coleta abaixo: <br />
                <br />
                • Av. Edvaldo Paraíso, 347 (sede provisória)
                <br />
                • Farma Center
                <br />
                • Farmácia Aras (Sta. Luz) <br />
                • Farmácia Popular <br />
                • Farmácia Mercês
                <br />
                • Farmácia do Paulo Farmácia Santana (Sta. Luz) <br />
                • Supermercado Compre Fácil <br />• Supermercado Santiago (Maria
                de Zé Valdo)
              </p>
            </Col>
          </Row>
        </Container>
        <Container className="mt-5">
          <Row>
            <Col xs={12}>
              <h2>Anjos Solidários na Mídia</h2>
              <p>Algumas matérias que fomos destaques</p>
            </Col>
            <Col xs={12} md={4} className={styles.article}>
              <Link
                href="https://avozdocampo.com/araci-grupo-anjos-solidarios-recebe-doacoes-de-fraldas-geriatricas-para-ajudar-necessitados/"
                rel="noopener noreferrer"
                target="_blank"
              >
                <div className={styles.text}>
                  <h3>
                    Araci: Grupo Anjos Solidários recebe doações de fraldas
                    geriátricas para ajudar necessitados
                  </h3>
                  <h4>Site: A Voz do Campo</h4>
                </div>
              </Link>
            </Col>
            <Col xs={12} md={4} className={styles.article}>
              <Link
                href="https://avozdocampo.com/anjos-solidarios-drive-thru-arrecada-fraldas-geriatricas-nesta-quinta-feira06-no-centro-de-araci/"
                rel="noopener noreferrer"
                target="_blank"
              >
                <div className={styles.text}>
                  <h3>
                    Anjos Solidários: Drive thru arrecada fraldas geriátricas
                    nesta quinta-feira (06) no centro de Araci
                  </h3>
                  <h4>Site: A Voz do Campo</h4>
                </div>
              </Link>
            </Col>
            <Col xs={12} md={4} className={styles.article}>
              <Link
                href="https://avozdocampo.com/solidariedade-voluntarias-se-unem-e-criam-grupo-de-ajuda-social-em-araci-para-arrecadar-fraldas-geriatricas/"
                rel="noopener noreferrer"
                target="_blank"
              >
                <div className={styles.text}>
                  <h3>
                    Solidariedade: Voluntárias se unem e criam grupo de ajuda
                    social em Araci para arrecadar fraldas geriátricas
                  </h3>
                  <h4>Site: A Voz do Campo</h4>
                </div>
              </Link>
            </Col>
          </Row>
        </Container>
      </main>
      <Footer/>
    </>
  );
}
